### ISSUE TITLE
Option to turn game board horizontal?

### ISSUE THREAD

**Issue by corndog2000** [azlee/SequenceGame#1]
Would it be possible to add a client side option to turn the board horizontal. It would be easier to see the whole board at once on smaller screen like a laptop. The vertical board arrangement is good for mobile though.

**Comment by azlee** [comment]
Hi Joe, that is a good point - will keep this issue open and try to work on horizontal layout.

**Comment by corndog2000** [comment]
Hello, sorry, I closed the issue since I ended up implementing board rotation in my fork of the application. You can check out my code modifications here [https://github.com/corndog2000/SequenceGame](https://github.com/corndog2000/SequenceGame). I am also hosting my version of the game at [http://schroedlsequence.ddns.net/](http://schroedlsequence.ddns.net/).
